#!/usr/local/bin/python3.6

# standard pacakages
import os
import asyncio
import datetime

# 3rd party packages

import discord
from discord.ext import commands
from discord.ext.commands import bot
import logging

# myPackages
import common.channels as channels


LOG_FORMAT = "%(levelname)s %(asctime)s - %(message)s"
logging.basicConfig(filename="bot.log",
                    level=logging.WARNING, format=LOG_FORMAT)
logger = logging.getLogger()

# credential file for discord token
# windows path ../SSPD Secrets/
# on pi in same directory
token_file = open("dToken.txt", "r")
d_token = token_file.readline()


client = discord.Client()
bot = commands.Bot(command_prefix='&')

# -----Setup Bot Properties and Modules-----
@bot.event
# @commands.has_role("Moderators™")
async def on_ready():
    print("Intialising...")
    # initialise channel ids
    channels.general = bot.get_channel(266593626501545984)
    channels.modChannel = bot.get_channel(300045476554735618)
    channels.logChannel = bot.get_channel(373156271056224256)
    print("ID: " + str(bot.user.id))
    print(bot.user)

    for filename in os.listdir("./cogs"):
        if filename.endswith(".py"):
            bot.load_extension(f"cogs.{filename[:-3]}")

    await bot.change_presence(status=discord.Status.online, activity=discord.Game("Suppressing mutants"))

    print(bot.user.name + " Ready...")
# ----------------------

bot.run(d_token)
